### ISSUE TITLE
this.init is not a function

### ISSUE THREAD

**Issue by gcardozo123** [trodi/blockly-d.ts#1]
Hi,

I'm quite new to both Typescript and Javascript and I'm having some trouble trying to use this repository. I'm not sure if this is being caused by this definition generator but would be great if you could give me some pointers. 

This is the problem:

I was able to inject blockly properly using:
```typescript
this.workspace = Blockly.inject(DOMHandler.blocklyDiv,{toolbox: tBox}); 
this.workspace.addChangeListener(this.myUpdateFunction);
```
But when I try to get the code from the workspace:
```typescript
 public myUpdateFunction = (event:any) =>
 {
    let code:string = "no code yet";
    code = this.blJSGenerator.workspaceToCode(this.workspace);
    ...
```
I receive the TypeError: "this.init is not a function" from blockly_compressed.js
![capturar](https://cloud.githubusercontent.com/assets/9798466/26220906/f955d0f8-3bea-11e7-9102-73695a438331.PNG)

One thing that was different is that in Javascript I could just write:
```javascript
var code = Blockly.Javascript.workspaceToCode(this.workspace);
```
But in Typescript I needed to instantiate a Blockly Javascript Generator:
```typescript
this.blJSGenerator = new Blockly.Generator("JavaScript");
```
Is this a problem?

There are some people trying to help in [this thread](https://groups.google.com/forum/#!topic/blockly/-HE1LMwJjAo).

Thanks in advance.

**Comment by trodi** [comment]
@gcardozo123 You don't need to create your Javascript generator differently than you were doing it before in Javascript. Remember that valid Javascript is valid Typescript.
`var code = Blockly.JavaScript.workspaceToCode(this.workspace);`

Using the syntax you switched to will generate a new generator for Javascript, which I don't believe is your intention (You would do this if you were adding a new generator for a unsupported language or you wanted to overwrite the default generator for a language).
`this.blJSGenerator = new Blockly.Generator("<new-language>");`

Currently, this repo only creates the definition file for Blockly's **core** folder. Blockly's generators are located under the **generators** folder. This is why you would have gotten a Typescript TSC error when trans-compiling. You can do one of a couple things:

* You could suppress the TSC error. This isn't great, but you could do it to test and avoid seeing the TSC error (Note: TSC type errors don't prevent you from running the generated javascript, so you could also just run the code without the type cast and not worry about the TSC error).
  * (`var code = (<any>Blockly).JavaScript.workspaceToCode(this.workspace);`)
* You can extend the definition file to support this use case.
* The best option: You could extend support of this repo to generate a second definition file that is for the generators.
  * I don't use any of the built in generators, so I've never had a need to add it. I can walk you through a pull request to make the change. If there is demand, I may find time to add this support myself.

I hope this helps. @rachel-fenichel is correct in the linked email thread as well about creating generators in reference to your issue. Also, note that this is **not** a wrapper around Blockly. It it merely the Typescript definition files. Using it doesn't change how you interact with Blockly; it just gives you type safety.

**Comment by gcardozo123** [comment]
Thank you so much, your answer clarified a lot of things!

As I said, I'm quite new to both Javascript and Typescript, but I'm interested on learning how to create those definitions files myself, so I'm interested in your pull request walkthrough. 

Other things: 
1. When I used your definition generator, there were a couple of errors on the definition file. There were some typos and there were some cases where a method was extended, but it didn't have the same parameters of the base method, in those cases I just defined those parameters as optional. 
2. There were about 46 errors of undefined Closure modules/classes, in those cases I defined modules/classes like:
```typescript
declare module goog.math
{
    class Coordinate{}
    class Size {}
    class Rect{}
}

declare module goog.ui
{
    class Menu{}
    class MenuItem{}
   
}
declare module goog.ui.tree
{
    class BaseNode{}
    class TreeControl{}
    class TreeNode{}
}

declare module goog.events
{
    class BrowserEvent{}
}

declare module goog.html
{
    class SafeHtml{}
}

declare module goog.dom
{
   class DomHelper{} 
}
```
But considering that I wouldn't use those goog modules directly, I didn't create any methods for those classes. 

And at the end of the file I've included this because Webpack or VS Code was complaining about "blockly" not being a module:
```typescript
declare module "blockly" {
    export = Blockly;
}
```

Have I done right?

**Comment by gcardozo123** [comment]
Ok, I've changed my code from:
```typescript
code = this.blJSGenerator.workspaceToCode(this.workspace);
```

To:
```typescript
code = (<any>Blockly).Javascript.workspaceToCode(this.workspace);
```

And now this is the error:
![capturar](https://cloud.githubusercontent.com/assets/9798466/26248552/42ea03cc-3c79-11e7-91b4-7670824cffee.PNG)

The full class:
```typescript
export class BlCodeEditor
{
    public static LOOP_TRAP: number = 1000; 
    private workspace: Blockly.Workspace;

    constructor()
    {
    }

    public init(): void
    {
        BlToolboxLoader.loadXML("./libs/blockly/sf_toolboxes/basicToolbox.xml", this.injectBlockly);
        //Preventing problems with Blockly's sound preloader:
        Blockly.WorkspaceSvg.prototype.preloadAudio_ = function() {};
    }
    
    public injectBlockly = (xml:XMLHttpRequest) =>
    {
        var xmlDoc = xml.responseXML; 
        var tBox = xmlDoc.getElementsByTagName("xml")[0]; 

        if (tBox == null)
            alert("toolbox is null");

        var nodeToImport = xmlDoc.importNode(tBox, true);
        DOMHandler.mainDiv.appendChild(nodeToImport);
        
        this.workspace = Blockly.inject(DOMHandler.blocklyDiv,{toolbox: tBox});
        this.workspace.addChangeListener((event:any) => this.myUpdateFunction(event));
    }

    public myUpdateFunction = (event:any) =>
    {
        console.log("hi from myUpdateFunction ");
        let code:string = "no code yet";
        code = (<any>Blockly).Javascript.workspaceToCode(this.workspace);
        console.log("code: " + code);
        if (DOMHandler.codeArea != null)
        {
            DOMHandler.codeArea.value = code;
        }
    }
}
```

**Comment by gcardozo123** [comment]
Ok, I've changed my code from:
```typescript
code = this.blJSGenerator.workspaceToCode(this.workspace);
```

To:
```typescript
code = (<any>Blockly).Javascript.workspaceToCode(this.workspace);
```

And now this is the error:
![capturar](https://cloud.githubusercontent.com/assets/9798466/26248552/42ea03cc-3c79-11e7-91b4-7670824cffee.PNG)

The full class:
```typescript
export class BlCodeEditor
{
    public static LOOP_TRAP: number = 1000; 
    private workspace: Blockly.Workspace;

    constructor()
    {
    }

    public init(): void
    {
        BlToolboxLoader.loadXML("./libs/blockly/sf_toolboxes/basicToolbox.xml", this.injectBlockly);
        //Preventing problems with Blockly's sound preloader:
        Blockly.WorkspaceSvg.prototype.preloadAudio_ = function() {};
    }
    
    public injectBlockly = (xml:XMLHttpRequest) =>
    {
        var xmlDoc = xml.responseXML; 
        var tBox = xmlDoc.getElementsByTagName("xml")[0]; 

        if (tBox == null)
            alert("toolbox is null");

        var nodeToImport = xmlDoc.importNode(tBox, true);
        DOMHandler.mainDiv.appendChild(nodeToImport);
        
        this.workspace = Blockly.inject(DOMHandler.blocklyDiv,{toolbox: tBox});
        this.workspace.addChangeListener((event:any) => this.myUpdateFunction(event));
    }

    public myUpdateFunction = (event:any) =>
    {
        console.log("hi from myUpdateFunction ");
        let code:string = "no code yet";
        code = (<any>Blockly).Javascript.workspaceToCode(this.workspace);
        console.log("code: " + code);
        if (DOMHandler.codeArea != null)
        {
            DOMHandler.codeArea.value = code;
        }
    }
}
```

**Comment by trodi** [comment]
**Cannot read property 'workspaceToCode' of undefined** means `Blockly.Javascript` is not defined. This makes since because "Javascript", which should be "JavaScript". Note that the type cast we added `<any>` effectively removes any type safety on this line so it wouldn't have been able to catch this error. Also make sure you've included the extra javascript source file: `<script src="javascript_compressed.js"></script>`

Change your code to: `(<any>Blockly).JavaScript.workspaceToCode(this.workspace);`

**Comment by gcardozo123** [comment]
I just changed from "Javascript" to "JavaScript" and it's working now, thanks!
Is there a place where I can contact you in case I have more doubts? If you don't mind, of course.

Thanks again!

**Comment by trodi** [comment]
You're welcome; I'm glad I was able to help ⭐️ .

> Is there a place where I can contact you in case I have more doubts?
* If you have any more questions on how to use these d.ts files, the best thing to do is open up another issue so others can benefit from the knowledge share.
* If you have questions specific to Blockly, I'd suggest using their website/guides/github/mailing group.
* If you have questions about Typescript, here are some great references I'd recommend:
  * [Typescript Book](https://basarat.gitbooks.io/typescript/content/docs/getting-started.html)
  * [Microsoft Docs](https://www.typescriptlang.org/docs/home.html)
* For other topics, I can try to answer/point you in the correct direction.

> 1. When I used your definition generator, there were a couple of errors on the definition file. There were some typos and there were some cases where a method was extended, but it didn't have the same parameters of the base method, in those cases I just defined those parameters as optional.

This project programmatically generates the d.ts file from Blockly source. It depends on the JSDocs for correct method signatures. Often the JSDocs in Blockly source are incomplete in which case I've submitted PRs to the project to address (e.g., [example commit](https://github.com/google/blockly/commit/11906b753579ad81827ef4a507bd969f4c46255e)). They've always been open to these PRs as it improves their code base as well.

> 2. There were about 46 errors of undefined Closure modules/classes, in those cases I defined modules/classes like:

This is because Blockly uses Closure and you don't have a Closure d.ts file TSC can use. Last I checked, there wasn't an official d.ts file, though I believe there are some projects out there. What I've done in my projects, is simply add a goog.d.ts file where I've added any bits I needed similar to what you've provided above. As this shouldn't be part of blockly's d.ts file, I haven't added it to this repo.

> but I'm interested on learning how to create those definitions files myself, so I'm interested in your pull request walkthrough.

This repo uses another library to do the heavy lifting to create the d.ts files, so adding the d.ts files for the generators won't require much typescript knowledge. You'll just have to modify my [shell script](https://github.com/trodi/blockly-d.ts/blob/master/npm-scripts/generate.sh). Please create another issue ~"Add support for language generator definitions" and we can go over any questions you have in making the changes etc.

> declare module "blockly" {
    export = Blockly;
}

This looks correct to allow you to `import * as Blockly from "blockly"`. I'd accept a PR to add support for this in the script as well if you are interested
