### ISSUE TITLE
Simple example

### ISSUE THREAD

**Issue by greatbiggiantbrain** [trodi/blockly-d.ts#6]
Could you please provide a simple example of what perhaps defining a simple block would look like?  I'm new to Typescript and am dabbling in trying to use it with Blockly (and obviously stuck).  Here is what I have so far (that is not working):

```
///<reference path="../blockly-core.d.ts" />

class simple_block {
  iterator: number = 0;

  constructor() {
    Blockly.Blocks['simple_block'] = {
      init: this.init(),
    };
  }

  init(): void{
    this.appendDummyInput()
      .appendField("some text")
      .appendField(new Blockly.FieldTextInput(''), 'TEXT')
      .appendField("some more text");
    this.setOutput(true, 'String');

  }
}
```

**Comment by trodi** [comment]
You'll have to create blocks in the manner Blockly expects. Checkout their [docs on creating blocks with javascript](https://developers.google.com/blockly/guides/create-custom-blocks/define-blocks#json_format_versus_javascript_api) for a good starting place.

`Blockly.Blocks` is an array of block type definitions. When you add a block definition to it, Blockly will be able to build your block custom block type. Therefore, you can't build a block class like you've done above.

In order to call the functions from `this` in init, `this` must be the `this` provided by the Blockly context, not captured by some typescript context. This should work in your code:
```typescript
Blockly.Blocks['simple_block'] = {
    init: (this: Blockly.Block): void {
        this.appendDummyInput()
        .appendField("some text")
        ...
        .appendField("some more text");
        this.setOutput(true, 'String');
    };
}
```
